---
version: '3.7'

volumes:
  war:
  archive:
  tomcat_logs:
  tomcat_work:
  tomcat_temp:





services:

  iip:
    image: antage/iipimage-server
    volumes:
      - "/srv/images:/srv:ro"
    environment:
      LOGFILE: '/tmp/iip.log'
      VERBOSITY: '6'
      FILESYSTEM_PREFIX: '/srv'
      WATERMARK: '/srv/watermark.tif'
      WATERMARK_PROBABILITY: '.5'
      WATERMARK_OPACITY: '.5'
      MAX_CVT: '500000'





  tei:
    image: 'tomcat:jdk17-corretto'
    command:
      - '/root/init.sh'
      - '/srv/genealogical-document-transcriptions/genealogy'
    volumes:
      - type: volume
        source: 'archive'
        target: '/srv'
        read_only: true
      - type: volume
        source: 'war'
        target: '/root/war'
        read_only: true
      - type: bind
        source: './tei/tomcat/init.sh'
        target: '/root/init.sh'
        read_only: true
      - type: bind
        source: './tei/tomcat/conf'
        target: '/usr/local/tomcat/conf'
        read_only: true
      - type: volume
        source: tomcat_logs
        target: '/usr/local/tomcat/logs'
      - type: volume
        source: tomcat_work
        target: '/usr/local/tomcat/work'
      - type: volume
        source: tomcat_temp
        target: '/usr/local/tomcat/temp'
    healthcheck:
      test: 'curl -f http://localhost:8080/health'
      interval: 10s
      timeout: 2s
      retries: 1
      start_period: 3s

  war:
    image: alpine
    volumes:
      - type: volume
        source: 'war'
        target: '/root/war'
    entrypoint:
      - '/bin/sh'
      - '-c'
    command:
      - >
        apk add maven &&
        mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get \
            -Dartifact=nu.mine.mosher.servlet:xml-servlet:LATEST:war &&
        cp -v ~/.m2/repository/nu/mine/mosher/servlet/xml-servlet/*/* /root/war/ &&
        touch /root/war/ready

  archive:
    image: alpine
    volumes:
      - type: volume
        source: 'archive'
        target: '/srv'
    entrypoint:
      - '/bin/sh'
      - '-c'
    command:
      - >
        apk add git &&
        cd /srv &&
        git clone --depth=1 https://github.com/cmosher01/genealogical-document-transcriptions.git





  uniwebfonts:
    image: cmosher01/universal-web-fonts

  unicode:
    image: cmosher01/unicode-web-test





  ftm-web-view:
    image: cmosher01/ftm-web-view
    environment:
#      ftm_public_access: 'public'
      ftm_dir: '/srv'
      CLIENT_ID: "${CLIENT_ID}"
      FTM_COPYRIGHT: "Copyright © 1998–2022, by Christopher Alan Mosher, Shelton, Connecticut, USA, https://mosher.mine.nu , mailto:cmosher01@gmail.com . This work is licensed under a CC BY-SA 4.0 license."
    volumes:
      - '/srv/ftm:/srv:ro'





  nginx:
    image: nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '/etc/letsencrypt/live/mosher.mine.nu:/etc/nginx/keys/live/mosher.mine.nu:ro'
      - '/etc/letsencrypt/archive/mosher.mine.nu:/etc/nginx/keys/archive/mosher.mine.nu:ro'
      - './mosher.mine.nu:/srv:ro'
      - '/srv/ftm:/srv/ftm:ro'
      - '/srv/vep:/srv/vep:ro'
      - '/srv/audio:/srv/audio:ro'
      - '/srv/doc:/srv/doc:ro'
    ports:
      - "80:80"
      - "443:443"
