---
version: '3'

volumes:
  tei:





services:
  fetch-tei:
    image: alpine
    entrypoint:
      - /root/fetch-tei.sh
    command:
      - 'ssh://git@github.com/cmosher01/genealogical-document-transcriptions.git'
    volumes:
      - '~/.ssh/id_rsa:/root/.ssh/id_rsa:ro'
      - '~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro'
      - './fetch-tei.sh:/root/fetch-tei.sh:ro'
      - "tei:/root/tei"

  tei:
    image: cmosher01/tei-server
    volumes:
      - "tei:/home/user:ro"





  iip:
    image: antage/iipimage-server
    volumes:
      - "/srv/images:/srv:ro"
    environment:
      LOGFILE: '/tmp/iip.log'
      VERBOSITY: '6'
      FILESYSTEM_PREFIX: '/srv'
      WATERMARK: '/srv/watermark.tif'
      WATERMARK_PROBABILITY: '.5'
      WATERMARK_OPACITY: '.5'
      MAX_CVT: '500000'





  uniwebfonts:
    image: cmosher01/universal-web-fonts

  unicode:
    image: cmosher01/unicode-web-test





  ftm-web-view:
    image: cmosher01/ftm-web-view
    environment:
      ftm_dir: '/srv'
      CLIENT_ID: "${CLIENT_ID}"
    volumes:
      - '/srv/ftm:/srv:ro'





  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - '/etc/letsencrypt/live/mosher.mine.nu:/etc/nginx/keys/live/mosher.mine.nu:ro'
      - '/etc/letsencrypt/archive/mosher.mine.nu:/etc/nginx/keys/archive/mosher.mine.nu:ro'
      - './mosher.mine.nu:/srv:ro'
      - '/srv/ftm:/srv/ftm:ro'
      - '/srv/vep:/srv/vep:ro'
      - '/srv/audio:/srv/audio:ro'
    ports:
      - "80:80"
      - "443:443"
